"""QA: the 50 real-world SME case studies and the universal client acceptance checklist.

The acceptance document defines what "100/100" means in practice: 50 production
acceptance scenarios and a checklist of 204 checks in 21 sections (A to U), plus a
final 30-day test. This module is that document as data, with an honest verdict for
every check, and the internal dashboard's QA page shows it
(``GET /api/internal/acceptance``). The cases also need sector capabilities the
checklist does not name (payouts, cost centers, deposits, ...): those are the X checks.

Verdicts
--------
``pass``     works in the engine and is proven by at least one named automated test.
``partial``  some of it works, or it is built but not connected, or it needs
             accounts or keys the product does not have yet.
``missing``  not built.

``tests/test_acceptance.py`` keeps the verdicts honest: every ``pass`` must cite a
test that exists (a Python test function, or a mobile ``it("...")`` case), every
cited file must exist, and every case must point only at checks defined here.
Whoever changes what the product can do updates the verdict here in the same change.

A case passes only when its PASS test is met *and* everything it must handle passes.
Its PASS test is met when every check that test depends on passes; it is not met
when none of them is built.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

__all__ = ["CASES", "CHECKS", "SECTIONS", "Case", "Check", "acceptance"]

Status = Literal["pass", "partial", "missing"]

# Where a check runs today.
DEMO = "Live demo"  # the engine the website runs (the production server runs the same engine)
SERVER = "Server"  # production server code: built and tested, not deployed
LIBRARY = "Library"  # built and tested, not connected to the running product
MOBILE = "Mobile app"
WEB = "Web app"
INFRA = "Infrastructure"
NOWHERE = "Nowhere yet"


@dataclass(frozen=True, slots=True)
class Check:
    id: str
    text: str
    status: Status
    where: str
    note: str
    evidence: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Case:
    number: int
    title: str
    quote: str
    handles: tuple[tuple[str, str], ...]  # (what the case must handle, check id)
    pass_test: str
    decisive: tuple[str, ...]  # the checks the PASS test depends on


def _c(id_: str, text: str, status: Status, where: str, note: str = "", *evidence: str) -> Check:
    return Check(id_, text, status, where, note, tuple(evidence))


T = "tests/"

# --------------------------------------------------------------------------- the checklist (A to U)

SECTIONS: tuple[tuple[str, str, tuple[Check, ...]], ...] = (
    ("A", "Onboarding", (
        _c("A1", "User can begin without training.", "partial", WEB,
           "The flow is short and plain, but it has never been tried by a real owner with no help (§67).",
           "web/tests/e2e.py"),
        _c("A2", "Company identity is auto-populated where possible.", "missing", NOWHERE,
           "Nothing looks the company up from its tax number; the owner types name and number."),
        _c("A3", "Email connection takes one authentication flow.", "partial", SERVER,
           "Google and Microsoft sign-in flows are built. Needs Google and Microsoft app approval.",
           T + "test_server_http.py::test_mailbox_sign_in_for_a_named_address"),
        _c("A4", "Bank connection takes one authentication flow.", "partial", SERVER,
           "Open-banking link through GoCardless is built. Needs a provider contract and live keys.",
           T + "test_server_http.py::test_bank_link_through_gocardless"),
        _c("A5", "Accountant can be added in seconds.", "pass", SERVER,
           "The accountant's email is recorded in one step (no invitation email yet, see N).",
           T + "test_server_http.py::test_onboarding_company_and_accountant"),
        _c("A6", "No accounting chart setup is required from SME.", "pass", DEMO, "",
           T + "test_server_http.py::test_onboarding_company_and_accountant"),
        _c("A7", "No folder structure is required.", "pass", DEMO,
           "Mail is read wherever it is; nothing depends on a folder called Invoices.",
           T + "test_ingest_email.py::test_ingest_creates_evidence_for_message_and_every_file"),
        _c("A8", "No supplier-rule configuration is required.", "pass", DEMO,
           "Suppliers are recognised from bank wording and tax numbers.",
           T + "test_recon_suppliers.py::test_descriptors_normalize_to_canonical_keys"),
        _c("A9", "Historical learning begins automatically.", "partial", SERVER,
           "The first sync reads 90 days. The 12-month option is only an operator setting.",
           T + "test_server_sync.py::test_first_gmail_sync_reads_90_days_through_the_vault_and_is_replayable"),
        _c("A10", "Initial owner questions are minimized.", "pass", DEMO,
           "A new business's first run asks at most 4 questions; the rest are learned or wait.",
           T + "test_acceptance_small_gaps.py::test_the_first_run_asks_at_most_the_capped_questions_and_the_rest_are_learned_or_deferred"),
        _c("A11", "First visible value appears within five minutes.", "partial", DEMO,
           "Now measured from recorded milestones; not yet observed with a real owner.",
           T + "test_acceptance_small_gaps.py::test_onboarding_milestones_time_to_first_value_and_active_minutes_come_from_recorded_events"),
    )),
    ("B", "Email discovery", (
        _c("B1", "PDF attachments detected.", "pass", SERVER,
           "Read on the server; the website demo stores PDFs without reading them.",
           T + "test_ingest_email.py::test_ingest_creates_evidence_for_message_and_every_file",
           T + "test_server_replay_safety.py::test_attachments_inside_an_email_are_read_before_recording"),
        _c("B2", "Images detected.", "pass", SERVER, "Detected and stored; read when the OCR server is set up.",
           T + "test_ingest_microsoft.py::test_attachments_of_every_kind"),
        _c("B3", "Inline receipt images detected.", "pass", SERVER, "",
           T + "test_ingest_microsoft.py::test_attachments_of_every_kind"),
        _c("B4", "Invoice information inside email body detected.", "pass", DEMO, "Plain text, HTML-only and schema.org receipts.",
           T + "test_acceptance_links_body.py::test_invoice_written_only_in_the_email_body_becomes_a_document",
           T + "test_acceptance_links_body.py::test_a_body_that_only_mentions_the_invoice_makes_no_second_document"),
        _c("B5", "Attached .eml messages processed.", "pass", DEMO, "",
           T + "test_ingest_email.py::test_ingest_forwarded_email_creates_nested_evidence",
           T + "test_ingest_regressions.py::test_downloaded_email_file_is_ingested_as_an_email"),
        _c("B6", "Old thread attachments processed correctly.", "pass", SERVER,
           "A reply pointing at an earlier invoice fetches the thread's earlier messages.",
           T + "test_acceptance_links_body.py::test_earlier_thread_attachment_is_fetched_through_the_connector",
           T + "test_acceptance_links_body.py::test_microsoft_conversation_gives_the_earlier_messages_oldest_first"),
        _c("B7", "Relevant links/buttons detected.", "pass", DEMO, "Detected; following them is C1.",
           T + "test_ingest_email.py::test_portuguese_and_spanish_button_vocabulary"),
        _c("B8", "Spam/archive can be searched when authorized.", "partial", SERVER,
           "Archive is read; spam is off with no owner setting to allow it.",
           T + "test_ingest_microsoft.py::test_initial_sync_walks_delta_for_every_folder_including_children"),
        _c("B9", "Duplicate emails do not create duplicate expenses.", "pass", DEMO, "",
           T + "test_ingest_email.py::test_reingesting_the_same_message_is_idempotent",
           T + "test_ingest_email.py::test_same_pdf_in_two_emails_is_one_evidence_with_two_sightings"),
    )),
    ("C", "Web links and portals", (
        _c("C1", "Invoice links can be followed safely.", "pass", SERVER,
           "Opened by the server before recording; the website demo uses stored sample pages.",
           T + "test_acceptance_links_body.py::test_invoice_link_in_an_email_is_followed_and_ingested_with_full_provenance",
           T + "test_acceptance_links_body.py::test_replay_never_opens_a_link_again"),
        _c("C2", "Redirects handled.", "pass", SERVER, "",
           T + "test_ingest_links.py::test_every_redirect_hop_is_revalidated",
           T + "test_acceptance_links_body.py::test_redirect_chain_is_followed_hop_by_hop_for_a_link_shared_from_the_browser"),
        _c("C3", "Download files preserved.", "pass", SERVER, "",
           T + "test_acceptance_links_body.py::test_invoice_link_in_an_email_is_followed_and_ingested_with_full_provenance"),
        _c("C4", "HTML receipts captured.", "pass", SERVER, "",
           T + "test_acceptance_links_body.py::test_page_without_a_file_is_preserved_as_rendered_evidence_and_read"),
        _c("C5", "Login-required portals supported.", "partial", LIBRARY,
           "The portal framework exists; no real supplier portal adapter is written.",
           T + "test_ingest_portals.py::test_valid_session_skips_login"),
        _c("C6", "MFA interruptions resume correctly.", "missing", NOWHERE,
           "The owner is told to sign in; nothing resumes on its own after the code step."),
        _c("C7", "Expired links trigger alternative retrieval.", "pass", SERVER,
           "Searches, then asks the supplier; production needs the supplier-request permission and an email account.",
           T + "test_acceptance_links_body.py::test_expired_link_asks_the_supplier_and_counts_only_what_a_transport_accepted",
           T + "test_acceptance_links_body.py::test_expired_link_asks_nobody_when_the_invoice_is_already_on_file"),
        _c("C8", "Portal credentials never enter model prompts.", "pass", SERVER,
           "Sign-ins are sealed in the vault; no path sends them to a model.",
           T + "test_core_privacy.py::test_every_token_sent_out_was_issued_by_the_vault"),
        _c("C9", "Browser sessions are isolated.", "partial", LIBRARY,
           "Isolated workers are built; a real browser run is skipped in tests.",
           T + "test_ingest_links.py::test_isolated_worker_returns_the_page"),
        _c("C10", "Malicious URLs are blocked.", "pass", LIBRARY,
           "Blocked on the phone and in the link fetcher (which is not connected yet, see C1).",
           T + "test_ingest_links.py::test_unsafe_urls_are_blocked",
           T + "test_ingest_links.py::test_redirect_to_lookalike_domain_is_blocked",
           "mobile/src/share/__tests__/share.test.ts › refuses dangerous or malformed links"),
    )),
    ("D", "Mobile", (
        _c("D1", "Camera scan works in seconds.", "partial", MOBILE,
           "Uses the phone's own document scanner; never timed on a real device."),
        _c("D2", "Multi-page scan works.", "partial", MOBILE,
           "The phone sends pages as one capture; the server drops the page numbers, so pages arrive as separate files.",
           "mobile/src/scan/__tests__/session.test.ts › queues every page as one capture with page numbers and hints"),
        _c("D3", "Blur is detected.", "pass", MOBILE, "",
           "mobile/src/scan/__tests__/quality.test.ts › flags clearly blurred pages, even with sensor noise"),
        _c("D4", "Glare is detected.", "pass", MOBILE, "",
           "mobile/src/scan/__tests__/quality.test.ts › flags a clipped highlight on ordinary paper"),
        _c("D5", "Perspective corrected.", "partial", MOBILE,
           "Done by the phone's scanner plugin; not tested on a device."),
        _c("D6", "QR detected.", "pass", MOBILE, "Read on the phone and again from the photo on the server.",
           "mobile/src/scan/__tests__/session.test.ts › collects issues and QR codes per page; analyzer failures mean no opinion",
           T + "test_reading_golden.py::test_photo_qr_code_and_ocr_agree_so_the_receipt_is_verified"),
        _c("D7", "Offline capture works.", "pass", MOBILE, "",
           "mobile/src/offline/__tests__/pipeline.test.ts › does nothing while offline and uploads once the network is back"),
        _c("D8", "Upload retries automatically.", "pass", MOBILE, "",
           "mobile/src/offline/__tests__/pipeline.test.ts › backs off exponentially on server errors and waits until the item is due"),
        _c("D9", "Local temporary evidence removed after confirmed upload.", "pass", MOBILE, "",
           "mobile/src/offline/__tests__/pipeline.test.ts › uploads sha256 + bytes, verifies the server hash, then deletes the local copy"),
        _c("D10", "Share from Gmail works.", "partial", MOBILE,
           "The app side is tested; the share extension is never built on a device, and an email shared as data fails on iPhone.",
           "mobile/src/share/__tests__/share.test.ts › accepts PDFs, images, screenshots, .eml and XML e-invoices"),
        _c("D11", "Share from Outlook works.", "partial", MOBILE, "Same as D10.",
           "mobile/src/share/__tests__/share.test.ts › accepts PDFs, images, screenshots, .eml and XML e-invoices"),
        _c("D12", "Share from WhatsApp works.", "partial", MOBILE,
           "Files and chat exports are accepted; the share extension is never built on a device.",
           T + "test_ingest_share.py::test_whatsapp_chat_export_zip_is_expanded"),
        _c("D13", "Share from Photos works.", "partial", MOBILE, "Same as D12.",
           T + "test_ingest_share.py::test_screenshot_and_photo_formats"),
        _c("D14", "Share from browser works.", "partial", MOBILE,
           "The server now follows a shared link; the phone's share extension is never built on a device.",
           "mobile/src/share/__tests__/share.test.ts › turns a bare link into a URL item the server will follow (§9)"),
        _c("D15", "User normally types nothing.", "pass", MOBILE, "No supplier, amount or category fields.",
           "mobile/src/scan/__tests__/session.test.ts › queues every page as one capture with page numbers and hints"),
    )),
    ("E", "OCR and extraction", (
        _c("E1", "Structured data used before OCR.", "pass", SERVER, "",
           T + "test_ocr_router.py::test_structured_evidence_settles_everything_and_ocr_is_skipped"),
        _c("E2", "Native PDF text extracted where available.", "pass", SERVER, "",
           T + "test_reading_golden.py::test_pdf_with_text_layer_is_verified_and_closes_after_the_bank_match"),
        _c("E3", "PP-OCRv6 supported.", "partial", SERVER,
           "The adapter is built and tested against a stand-in; the real model has never run. Needs an OCR server.",
           T + "test_reading_engines.py::test_sidecar_configured_by_env_reads_an_uploaded_photo"),
        _c("E4", "PaddleOCR-VL supported.", "partial", SERVER, "Same as E3.",
           T + "test_ocr_router.py::test_complex_layouts_escalate_to_paddleocr_vl"),
        _c("E5", "Unlimited-OCR supported for appropriate long/complex documents.", "partial", LIBRARY,
           "In the routing chain, but the server never registers it.",
           T + "test_ocr_router.py::test_long_documents_go_to_unlimited_ocr_when_fields_are_unsettled"),
        _c("E6", "OCR provider is replaceable.", "pass", SERVER, "",
           T + "test_ocr_router.py::test_engines_are_swapped_by_name"),
        _c("E7", "Paid OCR invoked only when economically justified.", "pass", SERVER,
           "Per-business monthly budget; it resets when the server restarts.",
           T + "test_ocr_router.py::test_tenant_budget_blocks_the_paid_step",
           T + "test_reading_golden.py::test_external_ai_is_not_called_when_local_reading_settles_everything"),
        _c("E8", "Tables extracted.", "partial", DEMO,
           "Invoice lines are read from e-invoices; not from PDFs or photos.",
           T + "test_acceptance_cost_centers.py::test_a_reseller_licence_invoice_is_split_across_its_customers_by_its_lines"),
        _c("E9", "Multilingual documents supported.", "partial", DEMO,
           "Portuguese, English and Spanish invoices are read; French, German and Italian labels are not yet.",
           T + "test_acceptance_foreign_documents.py::test_english_labels_keep_the_key_fields_on_one_line_or_many",
           T + "test_acceptance_foreign_documents.py::test_spanish_invoice_text_keeps_its_key_fields"),
        _c("E10", "Poor-quality scans escalated intelligently.", "partial", LIBRARY,
           "The router escalates; the server reader never passes image quality and drops the human step.",
           T + "test_ocr_router.py::test_poor_image_quality_escalates"),
        _c("E11", "Every critical field stores provenance.", "pass", DEMO, "",
           T + "test_reading_golden.py::test_photo_read_by_local_ocr_keeps_field_level_provenance",
           T + "test_ocr_structured.py::test_ubl_invoice_all_critical_fields_with_locations"),
    )),
    ("F", "Verification", (
        _c("F1", "Independent extraction sources compared.", "pass", DEMO, "",
           T + "test_verify_fields.py::test_section_19_ocr_qr_arithmetic_and_bank_agree_green",
           T + "test_verify_fields.py::test_the_same_engine_twice_is_not_independent"),
        _c("F2", "Mathematical totals verified.", "pass", DEMO, "",
           T + "test_verify_document.py::test_totals_that_do_not_add_up_turn_all_three_red"),
        _c("F3", "VAT calculations checked.", "pass", DEMO, "Portuguese rates only.",
           T + "test_verify_document.py::test_a_vat_rate_that_fits_nothing_keeps_the_vat_from_green",
           T + "test_verify_document.py::test_tax_lines_are_checked_and_must_match_the_totals"),
        _c("F4", "Invoice number verified.", "pass", DEMO, "",
           T + "test_verify_document.py::test_missing_required_fields_keep_the_document_amber"),
        _c("F5", "Supplier identity verified.", "pass", DEMO, "Tax number check digits and cross-source agreement.",
           T + "test_pt_country_pack.py::test_portugal_tax_ids_and_documents"),
        _c("F6", "Customer/legal entity verified.", "partial", DEMO,
           "Checked when present; required only for large first purchases.",
           T + "test_acceptance_engine_fixes.py::test_a_large_first_purchase_without_the_buyers_tax_number_stays_amber"),
        _c("F7", "Currency verified.", "pass", DEMO, "",
           T + "test_verify_regressions.py::test_same_number_in_two_currencies_is_a_conflict_not_a_match"),
        _c("F8", "Due date verified.", "pass", DEMO, "Checked against the issue date and other sources; overdue shown in plain words.",
           T + "test_acceptance_small_gaps.py::test_a_due_date_is_checked_against_the_issue_date_and_across_sources",
           T + "test_acceptance_small_gaps.py::test_an_unpaid_invoice_past_its_due_date_is_overdue_in_plain_words"),
        _c("F9", "QR compared when available.", "pass", DEMO, "",
           T + "test_verify_document.py::test_section_19_qr_says_438_60_red_conflict"),
        _c("F10", "Conflicting amounts never silently resolved.", "pass", DEMO,
           "The chat cannot settle a conflict either; only the owner's tap can.",
           T + "test_reading_golden.py::test_mismatching_qr_total_is_a_conflict_with_a_plain_question",
           T + "test_acceptance_honesty_fixes.py::test_claude_tools_refuse_to_settle_a_conflict"),
        _c("F11", "Uncertainty produces exception, not guess.", "pass", DEMO,
           "Covers pro-formas, the wrong company, cash receipts, large first purchases and clearly personal purchases.",
           T + "test_acceptance_small_gaps.py::test_a_personal_purchase_on_a_company_card_is_one_plain_question_with_always_learning",
           T + "test_acceptance_engine_fixes.py::test_a_payment_matched_only_to_a_pro_forma_stays_open_and_is_chased",
           T + "test_acceptance_engine_fixes.py::test_an_invoice_for_another_company_paid_from_the_wrong_account_asks_one_question"),
    )),
    ("G", "Duplicates", (
        _c("G1", "Exact file duplicates detected.", "pass", DEMO, "",
           T + "test_ingest_store.py::test_same_bytes_dedupe_and_add_sightings"),
        _c("G2", "Same invoice from multiple channels detected.", "pass", DEMO, "",
           T + "test_ingest_email.py::test_same_pdf_in_two_emails_is_one_evidence_with_two_sightings",
           T + "test_reading_golden.py::test_a_second_copy_that_disagrees_reopens_the_invoice_and_asks"),
        _c("G3", "Photo versus PDF duplicate detected.", "partial", SERVER,
           "Merged only when the photo's invoice number is read; no test covers it."),
        _c("G4", "Supplier+invoice-number duplicates detected.", "pass", DEMO, "",
           T + "test_reading_golden.py::test_a_second_copy_that_disagrees_reopens_the_invoice_and_asks"),
        _c("G5", "Near-duplicate credit notes are not incorrectly merged.", "pass", DEMO, "",
           T + "test_acceptance_engine_fixes.py::test_a_credit_note_with_its_invoices_number_is_not_merged_or_a_conflict"),
        _c("G6", "Canonical evidence object retains all original sources.", "pass", DEMO, "",
           T + "test_ingest_email.py::test_same_pdf_in_two_emails_is_one_evidence_with_two_sightings"),
    )),
    ("H", "Entity resolution", (
        _c("H1", "VAT/NIF used.", "pass", DEMO, "",
           T + "test_auto_learning_entity.py::test_invoice_addressee_is_documentary_evidence"),
        _c("H2", "Billing name used.", "pass", DEMO, "A vote that never overrides the tax number.",
           T + "test_acceptance_small_gaps.py::test_billing_name_address_and_mailbox_are_votes_with_plain_reasons",
           T + "test_acceptance_small_gaps.py::test_the_pipeline_uses_the_billing_name_and_address_on_an_invoice_without_a_tax_number"),
        _c("H3", "Address used.", "pass", DEMO, "",
           T + "test_acceptance_small_gaps.py::test_the_pipeline_uses_the_billing_name_and_address_on_an_invoice_without_a_tax_number"),
        _c("H4", "Bank/card source used.", "pass", DEMO, "",
           T + "test_auto_learning_entity.py::test_company_account_and_card_agree_green"),
        _c("H5", "Mailbox context used.", "pass", DEMO, "Set by the owner or learned; a shared mailbox is never learned.",
           T + "test_acceptance_small_gaps.py::test_a_mailbox_or_alias_is_learned_from_invoices_and_can_be_set_by_the_owner"),
        _c("H6", "Historical vendor behavior used.", "pass", DEMO, "",
           T + "test_auto_learning_entity.py::test_history_alone_is_amber_and_weak_disagreement_downgrades"),
        _c("H7", "Multiple entities supported.", "pass", DEMO, "",
           T + "test_api_service.py::test_companies_statuses"),
        _c("H8", "Intercompany transfers recognized.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_transfer_to_another_own_company_is_explained_as_such"),
        _c("H9", "Wrong-entity payments surfaced.", "pass", DEMO, "",
           T + "test_acceptance_engine_fixes.py::test_an_invoice_for_another_company_paid_from_the_wrong_account_asks_one_question"),
        _c("H10", "Entity uncertainty asks one simple question.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_one_tap_learning_resolves_similar_items_now_and_later"),
    )),
    ("I", "Bank reconciliation", (
        _c("I1", "One invoice / one payment.", "pass", DEMO, "",
           T + "test_recon_engine.py::test_one_to_one_verified_match_with_explanation"),
        _c("I2", "One invoice / several payments.", "pass", DEMO, "Closes on exact sums with references, or the owner's one tap.",
           T + "test_acceptance_deposits_milestones.py::test_milestone_payments_that_add_up_exactly_close_the_invoice",
           T + "test_acceptance_deposits_milestones.py::test_instalments_by_reference_close_in_the_pipeline"),
        _c("I3", "Several invoices / one payment.", "pass", DEMO, "",
           T + "test_recon_engine.py::test_one_payment_for_invoices_minus_a_credit_note"),
        _c("I4", "Deposits.", "pass", DEMO, "",
           T + "test_acceptance_deposits_milestones.py::test_a_supplier_deposit_is_taken_off_its_final_invoice",
           T + "test_acceptance_deposits_milestones.py::test_advance_invoice_and_final_invoice_take_the_deposit_off_once"),
        _c("I5", "Partial payments.", "pass", DEMO, "",
           T + "test_acceptance_deposits_milestones.py::test_a_part_payment_stays_open_with_a_plain_balance",
           T + "test_acceptance_deposits_milestones.py::test_a_part_payment_without_the_reference_is_one_question_then_the_owners_tap"),
        _c("I6", "Refunds.", "pass", DEMO, "Invoice, credit note and refund are linked and shown as one chain.",
           T + "test_acceptance_live_obligations.py::test_refund_chain_invoice_credit_note_refund_closes_and_is_visible",
           T + "test_acceptance_live_obligations.py::test_a_refund_of_another_amount_is_one_plain_question_not_a_close"),
        _c("I7", "Chargebacks.", "partial", DEMO,
           "Counted from payout reports; a chargeback on a bank statement is not recognised.",
           T + "test_acceptance_settlements.py::test_stripe_payout_with_fees_a_refund_and_a_dispute"),
        _c("I8", "Credit notes.", "pass", DEMO, "",
           T + "test_acceptance_engine_fixes.py::test_a_credit_note_is_netted_against_its_invoice"),
        _c("I9", "Card settlement batches.", "pass", DEMO, "Card-terminal payouts proven by the terminal's report.",
           T + "test_acceptance_settlements.py::test_card_terminal_batch_payout_closes_with_the_sibs_report"),
        _c("I10", "Payment processor settlements.", "pass", DEMO,
           "Report layouts follow the providers' public formats; not yet checked against real exports.",
           T + "test_acceptance_settlements.py::test_stripe_payout_with_fees_a_refund_and_a_dispute",
           T + "test_acceptance_settlements.py::test_each_provider_layout_is_read_into_the_same_figures"),
        _c("I11", "FX differences.", "partial", LIBRARY,
           "A dollar or pound invoice closes against the euro charge using the bank's exchange line; exchange differences are not recorded and spending totals leave foreign payments out.",
           T + "test_acceptance_foreign_documents.py::test_aws_invoice_in_dollars_closes_against_the_euro_card_charge_and_its_fx_line"),
        _c("I12", "Bank fees.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_fee_kind_from_the_bank_is_certain"),
        _c("I13", "Own-account transfers.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_transfer_between_own_accounts_needs_nothing"),
    )),
    ("J", "Expected evidence", (
        _c("J1", "Supplier purchases expect invoices.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_known_supplier_debit_expects_an_invoice"),
        _c("J2", "Taxes expect appropriate tax/payment evidence.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_tax_authorities_expect_a_notice_or_proof"),
        _c("J3", "Payroll expects payroll evidence.", "pass", DEMO, "Closed only by that month's payslip for that employee.",
           T + "test_acceptance_small_gaps.py::test_a_salary_to_the_employees_account_closes_only_on_that_months_payslip",
           T + "test_acceptance_small_gaps.py::test_a_payslip_is_read_as_payroll_evidence_and_never_as_a_letter_or_an_invoice"),
        _c("J4", "Loan payments expect financing evidence.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_loan_repayment_expects_the_loan_statement"),
        _c("J5", "Inter-account transfers do not trigger invoice chasing.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_transfer_between_own_accounts_needs_nothing"),
        _c("J6", "Bank fees follow accountant/country policy.", "pass", DEMO, "",
           T + "test_recon_expected.py::test_fee_kind_from_the_bank_is_certain"),
        _c("J7", "Expected-document rules can be learned.", "pass", DEMO, "",
           T + "test_acceptance_small_gaps.py::test_the_owners_answer_this_never_has_an_invoice_is_learned_for_later_payments",
           T + "test_acceptance_small_gaps.py::test_an_accountant_rule_about_invoices_is_learned_and_limited_to_its_company"),
    )),
    ("K", "Missing documents", (
        _c("K1", "System notices missing evidence automatically.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_pipeline_outcomes_per_evidence_kind"),
        _c("K2", "Searches all email sources first.", "partial", LIBRARY,
           "The search order is built; no concrete email search is connected.",
           T + "test_auto_missing_autopilot.py::test_searches_run_in_spec_order_and_stop_at_first_verified"),
        _c("K3", "Searches cloud storage.", "missing", NOWHERE, "No Google Drive, OneDrive or Dropbox connector."),
        _c("K4", "Searches accounting software.", "missing", NOWHERE, "No accounting software connector."),
        _c("K5", "Searches supplier portal.", "partial", LIBRARY, "No real portal adapter (see C5).",
           T + "test_ingest_portals.py::test_sync_retrieves_only_new_documents"),
        _c("K6", "Uses recurring history.", "partial", LIBRARY, "In the search plan; not connected.",
           T + "test_auto_missing_autopilot.py::test_searches_run_in_spec_order_and_stop_at_first_verified"),
        _c("K7", "Contacts supplier automatically when permitted.", "partial", DEMO,
           "Sent through the real send path when a sender exists. Production has no setting yet to grant permission, and needs an email-sending account.",
           T + "test_acceptance_honesty_fixes.py::test_demo_supplier_request_goes_through_the_simulated_outbox",
           T + "test_acceptance_honesty_fixes.py::test_production_service_sends_a_waiting_request_only_through_its_mailer"),
        _c("K8", "Monitors response.", "partial", LIBRARY,
           "The waiting workflow is built and simulated; nothing starts it in production.",
           T + "test_wf_sim_missing_invoice.py::test_reply_found_by_thread_check_closes_without_any_signal"),
        _c("K9", "Processes returned document.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_chased_invoice_arrives_and_closes_the_payment"),
        _c("K10", "Verifies it.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_chased_invoice_arrives_and_closes_the_payment"),
        _c("K11", "Reconciles it.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_chased_invoice_arrives_and_closes_the_payment"),
        _c("K12", "Closes request automatically.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_chased_invoice_arrives_and_closes_the_payment"),
    )),
    ("L", "Recurring intelligence", (
        _c("L1", "Recurring suppliers learned.", "pass", DEMO, "",
           T + "test_auto_learning_recurrence.py::test_monthly_invoice_series_learns_anchor_and_grace"),
        _c("L2", "Expected invoice dates learned.", "pass", DEMO, "",
           T + "test_auto_learning_recurrence.py::test_monthly_invoice_series_learns_anchor_and_grace"),
        _c("L3", "Usual amount ranges learned.", "pass", DEMO, "",
           T + "test_auto_learning_recurrence.py::test_subscription_increase_detected"),
        _c("L4", "Payment method learned.", "pass", DEMO, "",
           T + "test_acceptance_small_gaps.py::test_a_payment_series_remembers_the_usual_card_and_searches_it_first",
           T + "test_acceptance_small_gaps.py::test_a_payment_from_another_card_is_noted_not_held"),
        _c("L5", "Entity learned.", "pass", DEMO, "",
           T + "test_auto_learning_entity.py::test_history_alone_is_amber_and_weak_disagreement_downgrades"),
        _c("L6", "Portal retrieval path learned.", "missing", NOWHERE, "No real supplier portals are connected (see C5)."),
        _c("L7", "Missing recurring invoice detected proactively.", "pass", DEMO, "",
           T + "test_acceptance_live_obligations.py::test_an_overdue_usual_invoice_is_raised_once_asked_for_and_closed_when_it_arrives",
           T + "test_acceptance_live_obligations.py::test_nothing_is_expected_from_a_supplier_without_a_learned_rhythm"),
        _c("L8", "Abnormal recurring-price increases can be surfaced.", "pass", DEMO,
           "Shown in Ask, the accountant view and the audit; not on Home.",
           T + "test_auto_learning_recurrence.py::test_subscription_increase_detected",
           T + "test_api_assistant.py::test_supplier_summary_flags_price_increase_and_states_coverage"),
    )),
    ("M", "Administrative obligations", (
        _c("M1", "Tax deadlines detected.", "pass", DEMO, "From tax letters; there is no statutory calendar.",
           T + "test_close_obligations.py::test_portuguese_tax_letter_becomes_a_complete_obligation"),
        _c("M2", "Insurance renewals detected.", "pass", DEMO, "A policy that renews on its own is shown as information only.",
           T + "test_acceptance_live_obligations.py::test_insurance_that_renews_on_its_own_stays_information_only"),
        _c("M3", "Contract renewals detected.", "pass", DEMO, "",
           T + "test_acceptance_live_obligations.py::test_english_contract_renewal_is_done_by_the_confirmed_ending"),
        _c("M4", "Licensing requirements detected.", "pass", DEMO, "",
           T + "test_acceptance_live_obligations.py::test_licence_renewal_closes_only_on_the_renewed_licence"),
        _c("M5", "Government requests detected.", "pass", DEMO, "",
           T + "test_acceptance_live_obligations.py::test_government_request_and_filing_close_on_the_tax_offices_confirmation"),
        _c("M6", "KYC requests detected.", "pass", DEMO, "",
           T + "test_acceptance_live_obligations.py::test_kyc_request_by_email_is_tracked_everywhere_and_done_only_by_the_banks_confirmation"),
        _c("M7", "Accountant requests detected.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_pipeline_outcomes_per_evidence_kind"),
        _c("M8", "Obligation has owner/responsible person.", "pass", DEMO, "",
           T + "test_close_obligations.py::test_filing_goes_to_the_accountant"),
        _c("M9", "Deadline stored.", "pass", DEMO, "",
           T + "test_close_obligations.py::test_portuguese_tax_letter_becomes_a_complete_obligation"),
        _c("M10", "Required proof defined.", "pass", DEMO, "",
           T + "test_close_obligations.py::test_detected_obligation_can_be_satisfied_end_to_end"),
        _c("M11", "Completion verified.", "pass", DEMO, "",
           T + "test_close_obligations.py::test_detected_obligation_can_be_satisfied_end_to_end",
           T + "test_acceptance_live_obligations.py::test_a_confirmation_from_another_sender_or_a_follow_up_request_never_closes_it",
           T + "test_close_obligations.py::test_likely_proof_never_closes_an_obligation"),
    )),
    ("N", "Accountant experience", (
        _c("N1", "Accountant sees all clients.", "pass", SERVER,
           "Every client company the accountant was given, across businesses; the demo shows its own companies.",
           T + "test_acceptance_accountant.py::test_an_accountant_reading_from_their_own_firm_sees_only_the_companies_they_were_given"),
        _c("N2", "Completion status visible immediately.", "pass", DEMO, "",
           T + "test_api_service.py::test_accountant_clients_and_detail"),
        _c("N3", "Missing items visible.", "pass", DEMO, "",
           T + "test_api_service.py::test_accountant_clients_and_detail"),
        _c("N4", "Evidence linked.", "pass", DEMO, "",
           T + "test_acceptance_accountant.py::test_client_view_shows_evidence_links_and_the_reconciliation"),
        _c("N5", "Bank reconciliation available.", "pass", DEMO, "",
           T + "test_acceptance_accountant.py::test_client_view_shows_evidence_links_and_the_reconciliation"),
        _c("N6", "Accountant can teach rules.", "pass", DEMO, "Understands \"Treat X as Y\" phrasing.",
           T + "test_api_service.py::test_accountant_rule",
           T + "test_acceptance_honesty_fixes.py::test_accountant_rule_and_export_are_real"),
        _c("N7", "Accountant questions can be answered automatically.", "pass", DEMO,
           "Answers only what the evidence supports, and only counts it answered once delivered.",
           T + "test_acceptance_honesty_fixes.py::test_demo_rent_question_is_answered_from_the_receipt_and_delivered",
           T + "test_acceptance_honesty_fixes.py::test_claims_the_evidence_does_not_support_are_never_confirmed"),
        _c("N8", "Client intervention occurs only where needed.", "pass", DEMO, "",
           T + "test_acceptance_honesty_fixes.py::test_a_decision_question_stays_open_even_when_its_payment_closes"),
        _c("N9", "Monthly package exports reliably.", "partial", DEMO,
           "On-demand ZIP with booked and supporting documents; no scheduled delivery and no SAF-T export.",
           T + "test_acceptance_engine_fixes.py::test_accountant_export_marks_supporting_documents_as_not_booked"),
        _c("N10", "Delivery/receipt is verified.", "partial", LIBRARY,
           "Delivery tracking is built; nothing sends the package.",
           T + "test_close_package.py::test_delivery_moves_from_prepared_to_delivered_to_confirmed"),
    )),
    ("O", "Multi-entity", (
        _c("O1", "One user can own multiple companies.", "pass", DEMO, "",
           T + "test_api_service.py::test_companies_statuses"),
        _c("O2", "Shared inbox supported.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_one_tap_learning_resolves_similar_items_now_and_later"),
        _c("O3", "Shared supplier supported.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_one_tap_learning_resolves_similar_items_now_and_later"),
        _c("O4", "Separate banks supported.", "pass", DEMO, "",
           T + "test_auto_learning_entity.py::test_company_account_and_card_agree_green"),
        _c("O5", "Separate accountants supported.", "pass", DEMO, "Each company can have its own accountant; the business's is the default.",
           T + "test_acceptance_accountant.py::test_each_company_can_have_its_own_accountant_and_the_business_one_is_the_default",
           T + "test_acceptance_accountant.py::test_accountant_questions_are_filed_under_the_asking_accountants_company"),
        _c("O6", "Separate jurisdictions supported.", "missing", NOWHERE, "Every company is set to Portugal."),
        _c("O7", "Evidence never leaks between entities.", "pass", SERVER,
           "Between businesses, and between companies for an accountant limited to some of them.",
           T + "test_infra_postgres.py::test_a_tenant_sees_only_its_own_rows",
           T + "test_server_http.py::test_one_business_can_never_read_another",
           T + "test_acceptance_cost_centers.py::test_evidence_never_leaks_across_companies",
           T + "test_acceptance_accountant.py::test_an_accountant_of_company_b_cannot_read_company_a_through_any_get_route"),
        _c("O8", "Global owner dashboard available.", "pass", DEMO, "",
           T + "test_api_service.py::test_home_matches_contract_and_is_computed"),
    )),
    ("P", "Country packs", (
        _c("P1", "Core remains jurisdiction-neutral.", "partial", DEMO,
           "The core imports the Portugal pack directly and hard-codes Portugal for new companies."),
        _c("P2", "Portugal rules isolated in Portugal pack.", "partial", DEMO,
           "Mostly in countries/pt; some Portuguese wording lives in the core.",
           T + "test_pt_country_pack.py::test_portugal_tax_ids_and_documents"),
        _c("P3", "Country-specific VAT rules supported.", "pass", DEMO, "Portugal only.",
           T + "test_pt_country_pack.py::test_portugal_vat_through_the_protocol"),
        _c("P4", "Country-specific identifiers supported.", "pass", DEMO, "Portugal only.",
           T + "test_pt_country_pack.py::test_portugal_tax_ids_and_documents"),
        _c("P5", "Country-specific fiscal documents supported.", "pass", DEMO,
           "Portuguese invoice QR, ATCUD and SAF-T reading.",
           T + "test_pt_country_pack.py::test_portugal_fiscal_qr_through_the_protocol",
           T + "test_pt_saft.py::test_reads_invoices_and_header"),
        _c("P6", "Country-specific deadlines supported.", "partial", DEMO,
           "Deadlines come from letters; there is no statutory calendar."),
        _c("P7", "Foreign documents can coexist with local company.", "pass", DEMO,
           "Checked by the issuer's own country's rules. The foreign VAT-rate table is not yet checked against official sources.",
           T + "test_acceptance_foreign_documents.py::test_meta_ads_invoice_from_ireland_closes_green_against_the_card_charge",
           T + "test_acceptance_foreign_documents.py::test_booking_com_commission_from_the_netherlands_closes_against_the_direct_debit",
           T + "test_acceptance_foreign_documents.py::test_portuguese_invoices_are_read_and_checked_by_the_portuguese_rules"),
    )),
    ("Q", "Fraud and risk", (
        _c("Q1", "Changed IBAN triggers hard stop.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_changed_iban_blocks_payment_and_matching"),
        _c("Q2", "New beneficiary triggers verification.", "pass", DEMO, "",
           T + "test_auto_fraud_engine.py::test_new_supplier_is_a_new_payment_recipient"),
        _c("Q3", "Suspicious email domain detected.", "pass", DEMO, "",
           T + "test_auto_fraud_engine.py::test_lookalike_domain_is_critical"),
        _c("Q4", "Duplicate invoice with altered bank data blocked.", "pass", DEMO, "",
           T + "test_auto_fraud_engine.py::test_duplicate_with_different_iban_is_critical"),
        _c("Q5", "Unusual amount surfaced.", "pass", DEMO, "",
           T + "test_auto_fraud_engine.py::test_unusual_high_amount_is_a_hard_stop",
           T + "test_acceptance_engine_fixes.py::test_a_large_first_purchase_without_the_buyers_tax_number_stays_amber"),
        _c("Q6", "Unusual currency/country surfaced.", "pass", DEMO, "",
           T + "test_auto_fraud_engine.py::test_unusual_iban_country",
           T + "test_acceptance_foreign_documents.py::test_an_invoice_in_a_currency_the_supplier_never_used_is_a_check_not_a_hard_stop",
           T + "test_acceptance_foreign_documents.py::test_bank_details_whose_country_does_not_fit_the_currency_are_a_check"),
        _c("Q7", "Payment actions require proper approval.", "pass", DEMO, "",
           T + "test_core_policy_actions.py::test_levels_match_spec_section_25",
           T + "test_core_policy_actions.py::test_hard_approval_must_be_bound_to_the_facts_it_approved"),
        _c("Q8", "AI can never autonomously approve beneficiary changes.", "pass", DEMO, "",
           T + "test_auto_fraud_beneficiary.py::test_engine_cannot_receive_approvals",
           T + "test_acceptance_honesty_fixes.py::test_rule_brain_never_answers_an_approval_as_a_choice"),
    )),
    ("R", "Connection health", (
        _c("R1", "Email sync monitored.", "pass", SERVER, "",
           T + "test_server_sync.py::test_a_mailbox_that_stops_syncing_for_a_day_is_shown_to_the_owner"),
        _c("R2", "Bank sync monitored.", "pass", DEMO, "",
           T + "test_orchestrator_pipeline.py::test_stale_connector_keeps_the_month_from_green"),
        _c("R3", "Accounting sync monitored.", "missing", NOWHERE, "No accounting software connection exists."),
        _c("R4", "Token expiry monitored.", "pass", SERVER, "",
           T + "test_server_sync.py::test_a_refused_sign_in_marks_the_mailbox_for_the_owner_once"),
        _c("R5", "Webhook loss detected.", "partial", LIBRARY, "There is no webhook receiver yet.",
           T + "test_ingest_gmail.py::test_watch_and_push_notifications"),
        _c("R6", "Periodic backfill occurs.", "partial", LIBRARY, "Gaps are recorded but never backfilled.",
           T + "test_ingest_gmail.py::test_backfill_reads_the_gap_and_closes_it"),
        _c("R7", "Failed sync prevents false “all clear.”", "pass", DEMO, "",
           T + "test_close_month.py::test_a_connector_that_stopped_syncing_keeps_the_month_from_ever_being_green",
           T + "test_orchestrator_pipeline.py::test_stale_connector_keeps_the_month_from_green"),
        _c("R8", "Reconnect experience is one-click/simple.", "pass", SERVER, "",
           T + "test_acceptance_honesty_fixes.py::test_production_reconnect_hands_out_the_sign_in_address_and_claims_nothing"),
    )),
    ("S", "Resilience", (
        _c("S1", "All ingestion is idempotent.", "pass", DEMO, "",
           T + "test_ingest_email.py::test_reingesting_the_same_message_is_idempotent",
           T + "test_infra_postgres.py::test_same_bytes_twice_is_one_evidence_per_tenant"),
        _c("S2", "Duplicate webhook events harmless.", "partial", LIBRARY, "No webhook receiver yet."),
        _c("S3", "Retries implemented.", "pass", SERVER, "",
           T + "test_server_sync.py::test_outages_are_retried_with_backoff_and_record_nothing"),
        _c("S4", "Backoff implemented.", "pass", SERVER, "",
           T + "test_server_sync.py::test_outages_are_retried_with_backoff_and_record_nothing"),
        _c("S5", "Dead-letter handling exists.", "partial", INFRA,
           "Dead-letter queues and alarms are provisioned; no code uses the queues."),
        _c("S6", "System recovers after downtime.", "pass", SERVER, "",
           T + "test_server_runtime.py::test_replay_rebuilds_every_read_exactly"),
        _c("S7", "Missed periods are backfilled.", "partial", LIBRARY, "Same as R6.",
           T + "test_ingest_gmail.py::test_backfill_reads_the_gap_and_closes_it"),
        _c("S8", "No transaction/document silently disappears.", "partial", SERVER,
           "Bank rows for an account the business has not added are dropped with only a count."),
    )),
    ("T", "UX", (
        _c("T1", "Owner understands home screen instantly.", "partial", WEB, "Not tested with owners yet."),
        _c("T2", "“Needs You” contains only actual decisions.", "pass", DEMO, "",
           T + "test_api_service.py::test_needs_you_shapes"),
        _c("T3", "Accounting jargon removed.", "pass", DEMO, "Engine wording is checked; web page copy is not.",
           T + "test_core_language.py::test_every_owner_facing_string_is_plain_and_calm"),
        _c("T4", "Green means genuinely complete.", "pass", DEMO, "",
           T + "test_close_month.py::test_amber_is_never_counted_as_done",
           T + "test_close_metrics.py::test_home_percent_never_reaches_100_before_every_company_closes"),
        _c("T5", "Amber means unresolved/uncertain.", "pass", DEMO, "",
           T + "test_close_month.py::test_amber_is_never_counted_as_done"),
        _c("T6", "Red reserved for real risk.", "partial", WEB, "Followed by design; no automated check."),
        _c("T7", "Settings rarely required.", "partial", WEB, "Not measured."),
        _c("T8", "User can ask natural-language questions.", "pass", DEMO, "",
           T + "test_chat_understanding.py::test_owner_phrasings"),
        _c("T9", "Every answer links to evidence.", "pass", DEMO, "",
           T + "test_api_service.py::test_ask_routes_and_cites_evidence"),
        _c("T10", "UI remains visually calm even with complex backend activity.", "partial", WEB,
           "The desktop top bar has 8 items; the product specification allows 5."),
    )),
    ("U", "Product success", (
        _c("U1", "Owner active onboarding time <10 minutes.", "partial", DEMO,
           "Measured from recorded steps (estimated per step); no real owner has onboarded yet.",
           T + "test_acceptance_small_gaps.py::test_answers_to_first_run_questions_count_as_onboarding_time_and_later_answers_do_not"),
        _c("U2", "First value <5 minutes.", "partial", DEMO,
           "Measured from recorded milestones; the app does not yet record when the owner saw the time saved.",
           T + "test_acceptance_small_gaps.py::test_onboarding_milestones_time_to_first_value_and_active_minutes_come_from_recorded_events"),
        _c("U3", "Zero-touch routine processing >95%.", "partial", DEMO,
           "Measured on the demo business (Targets page); below target.",
           T + "test_internal.py::test_zero_touch_is_closed_without_owner_over_all_items"),
        _c("U4", "Critical silent financial errors = 0.", "partial", DEMO,
           "The silent errors found by this QA pass were fixed; nothing counts silent errors automatically."),
        _c("U5", "Missing-document auto-resolution >90%.", "partial", DEMO, "Measured on the demo business only.",
           T + "test_internal.py::test_targets_list_every_success_metric"),
        _c("U6", "Month-end unresolved items <1%.", "partial", DEMO, "Measured on the demo business only.",
           T + "test_internal.py::test_targets_list_every_success_metric"),
        _c("U7", "Owner administration <15 minutes/month/entity.", "partial", DEMO,
           "Estimated at 40 seconds per tap; not measured."),
        _c("U8", "User stops maintaining invoice folders manually.", "partial", NOWHERE, "Needs real customers."),
        _c("U9", "User stops searching email manually.", "partial", NOWHERE, "Needs real customers."),
        _c("U10", "User stops chasing ordinary supplier invoices.", "partial", NOWHERE,
           "Production cannot send supplier requests yet (see K7)."),
        _c("U11", "User stops preparing monthly accountant packages manually.", "partial", NOWHERE,
           "The package is made on demand, not delivered on schedule (see N9)."),
    )),
)

# Sector capabilities the cases need beyond the checklist.
EXTRA: tuple[Check, ...] = (
    _c("X1", "Supplier invoices by email are collected and read.", "pass", DEMO, "",
       T + "test_ingest_email.py::test_supplier_invoice_email_is_fully_read"),
    _c("X2", "Photographed paper receipts are read without typing.", "partial", SERVER,
       "Read on the server with an OCR server; the website demo stores photos unread.",
       T + "test_reading_golden.py::test_photo_read_by_local_ocr_keeps_field_level_provenance"),
    _c("X3", "Cash purchases close on their receipt.", "pass", DEMO, "",
       T + "test_acceptance_engine_fixes.py::test_a_verified_cash_receipt_closes_as_a_cash_expense"),
    _c("X4", "Petty cash float tracked.", "missing", NOWHERE, "Cash receipts close one by one; no cash box balance."),
    _c("X5", "Cash sales evidenced.", "missing", NOWHERE, "Cash takings (till totals, cash deposits) are not recorded."),
    _c("X6", "Recurring rent and utilities handled.", "pass", DEMO, "",
       T + "test_auto_learning_recurrence.py::test_monthly_invoice_series_learns_anchor_and_grace",
       T + "test_ingest_email.py::test_supplier_invoice_email_is_fully_read"),
    _c("X7", "Software subscriptions learned and increases shown.", "pass", DEMO, "",
       T + "test_auto_learning_recurrence.py::test_subscription_increase_detected"),
    _c("X8", "Customer deposits, milestones and retention.", "pass", DEMO, "",
       T + "test_acceptance_deposits_milestones.py::test_deposit_then_final_invoice_then_balance_closes_the_wedding",
       T + "test_acceptance_deposits_milestones.py::test_retention_is_held_back_until_its_release_then_paid",
       T + "test_acceptance_deposits_milestones.py::test_income_answers_never_count_a_deposit_twice"),
    _c("X9", "Customer security deposits kept apart from revenue.", "partial", DEMO,
       "Deposits are named apart from sales and one given back counts as neither; a refundable security deposit is not marked as such.",
       T + "test_acceptance_deposits_milestones.py::test_a_cancelled_booking_deposit_is_given_back_and_linked"),
    _c("X10", "Client money passing through, disbursements and reimbursable costs.", "pass", DEMO,
       "Recharged costs and money held for clients are kept out of the business's own costs and income.",
       T + "test_acceptance_statements_rebilling.py::test_media_bought_for_a_client_is_inferred_from_the_invoice_and_left_out_of_own_costs",
       T + "test_acceptance_statements_rebilling.py::test_client_money_held_by_a_travel_agency_is_not_revenue",
       T + "test_acceptance_statements_rebilling.py::test_a_disbursement_on_behalf_of_a_client_is_theirs_to_pay_back"),
    _c("X11", "Revenue kept apart from expenses.", "pass", DEMO,
       "Own sales invoices and platform payouts are recognised as money in.",
       T + "test_acceptance_engine_fixes.py::test_own_sales_invoice_matches_the_customer_payment",
       T + "test_acceptance_settlements.py::test_payout_without_its_report_stays_open_asks_for_it_and_is_not_customer_revenue"),
    _c("X12", "Recurring customer payments (memberships, tuition, fees).", "partial", DEMO,
       "Customer payments expect a sales invoice; no membership or term concept.",
       T + "test_recon_engine.py::test_customer_payment_matches_our_sales_invoice"),
    _c("X13", "Delivery-platform and booking-platform payouts with commissions.", "pass", DEMO,
       "A foreign commission invoice (Booking.com, Netherlands) stays open (see P7).",
       T + "test_acceptance_settlements.py::test_booking_payout_net_of_commission_and_the_commission_invoice",
       T + "test_acceptance_settlements.py::test_delivery_platform_weekly_payouts_cover_many_orders"),
    _c("X14", "Cost centers: jobs, properties, vehicles, outlets, events, courses, clients.", "pass", DEMO, "",
       T + "test_acceptance_cost_centers.py::test_an_address_a_plate_and_a_project_code_on_the_invoice_name_the_cost_center",
       T + "test_acceptance_cost_centers.py::test_a_supplier_always_on_the_same_job_is_put_there_as_likely",
       T + "test_acceptance_cost_centers.py::test_each_cost_center_shows_what_it_cost_what_came_in_and_the_proof"),
    _c("X15", "One document split across customers or cost centers.", "pass", DEMO, "",
       T + "test_acceptance_cost_centers.py::test_a_reseller_licence_invoice_is_split_across_its_customers_by_its_lines",
       T + "test_acceptance_cost_centers.py::test_one_utility_bill_split_across_three_apartments_exact_to_the_cent"),
    _c("X16", "Employee cards: missing receipts asked from the cardholder.", "pass", DEMO,
       "Asked by email through the send path; production needs an email account. No push to employees yet.",
       T + "test_acceptance_employee_cards.py::test_a_missing_card_receipt_is_asked_from_the_cardholder_through_the_send_path_and_counts_only_when_accepted",
       T + "test_acceptance_employee_cards.py::test_no_answer_after_the_reminders_becomes_one_plain_line_for_the_owner_never_earlier"),
    _c("X17", "Staff expenses paid personally and reimbursed.", "pass", DEMO, "",
       T + "test_acceptance_employee_cards.py::test_an_expense_claim_needs_the_owners_one_tap_and_the_reimbursement_closes_it",
       T + "test_acceptance_employee_cards.py::test_a_staff_expense_is_counted_once_and_the_reimbursement_is_not_a_second_cost"),
    _c("X18", "Invoice versus delivery note, pro-forma, quote and supplier statement.", "pass", DEMO, "",
       T + "test_acceptance_engine_fixes.py::test_non_accounting_documents_are_their_own_kinds_and_close_nothing",
       T + "test_acceptance_engine_fixes.py::test_accountant_export_marks_supporting_documents_as_not_booked"),
    _c("X19", "Supplier statements reconciled to their invoices.", "pass", DEMO,
       "Checked line by line; documents it lists that are missing are asked for.",
       T + "test_acceptance_statements_rebilling.py::test_statement_is_checked_line_by_line_and_never_booked_or_duplicated",
       T + "test_acceptance_statements_rebilling.py::test_documents_on_the_statement_we_do_not_have_are_missing_and_asked_for_once",
       T + "test_acceptance_statements_rebilling.py::test_an_amount_difference_is_one_plain_question_never_a_silent_change"),
    _c("X20", "Price changes on raw materials (line level).", "partial", DEMO,
       "Price increases are seen per supplier; unit prices are not read from PDFs or photos.",
       T + "test_auto_learning_recurrence.py::test_subscription_increase_detected"),
    _c("X21", "Large purchases get stronger checks.", "pass", DEMO, "",
       T + "test_acceptance_engine_fixes.py::test_a_large_first_purchase_without_the_buyers_tax_number_stays_amber",
       T + "test_acceptance_engine_fixes.py::test_a_large_purchase_from_a_supplier_with_history_is_not_held"),
    _c("X22", "Equipment flagged as a possible capital asset for the accountant.", "pass", DEMO, "",
       T + "test_acceptance_engine_fixes.py::test_equipment_wording_above_the_threshold_is_flagged_but_routine_receipts_are_not"),
    _c("X23", "Personal purchase on a company card noticed.", "pass", DEMO, "Only for strong signals; ordinary suppliers are never asked.",
       T + "test_auto_learning_entity.py::test_personal_card_only_asks_and_answer_becomes_spec_rule",
       T + "test_acceptance_small_gaps.py::test_a_personal_purchase_on_a_company_card_is_one_plain_question_with_always_learning"),
    _c("X24", "Leasing contracts.", "partial", DEMO, "Treated like loan statements; no lease schedule.",
       T + "test_recon_expected.py::test_loan_repayment_expects_the_loan_statement"),
    _c("X25", "Owner statements for property owners.", "pass", DEMO, "",
       T + "test_acceptance_statements_rebilling.py::test_owner_statement_for_a_property_shows_rent_costs_fee_and_what_is_due",
       T + "test_acceptance_statements_rebilling.py::test_an_owner_statement_with_open_items_says_so_and_is_not_final"),
    _c("X26", "Tourist tax and similar local fees.", "missing", NOWHERE, "Not recognised or tracked as an obligation."),
    _c("X27", "Cloud and software vendors matched despite different bank wording.", "pass", DEMO, "",
       T + "test_recon_suppliers.py::test_descriptors_normalize_to_canonical_keys"),
    _c("X28", "Import chain: deposits, freight, customs, duties and final invoice linked.", "missing", NOWHERE, "Customs and freight documents are not linked to the purchase they belong to."),
    _c("X29", "Seasonal patterns.", "partial", DEMO, "Monthly patterns are learned; seasons are not.",
       T + "test_auto_learning_recurrence.py::test_monthly_invoice_series_learns_anchor_and_grace"),
    _c("X30", "Grant and subsidy letters detected.", "missing", NOWHERE, "Letters about grants and subsidies are not recognised."),
    _c("X31", "Reverse charge and foreign VAT.", "pass", DEMO, "Flagged for the accountant only.",
       T + "test_acceptance_foreign_documents.py::test_reverse_charge_and_foreign_vat_flags_reach_the_accountant_only"),
    _c("X32", "Sensitive documents protected with strict access.", "partial", SERVER,
       "Roles, row-level isolation and redaction before external AI exist; no sensitivity level per document or per-company access.",
       T + "test_server_auth.py::test_accountant_reads_and_teaches_rules_only",
       T + "test_reading_golden.py::test_external_ai_on_asks_claude_once_redacted_and_within_budget"),
    _c("X33", "High document volume handled reliably.", "partial", DEMO, "No volume or performance test."),
    _c("X34", "Processing cost low enough for tiny businesses.", "partial", SERVER,
       "Local OCR first and a paid-step budget; no measured cost per document.",
       T + "test_ocr_router.py::test_tenant_budget_blocks_the_paid_step"),
    _c("X35", "Low-volume plan and billing.", "missing", NOWHERE, "No billing yet."),
    _c("X36", "Accountant invites clients.", "pass", SERVER,
       "Needs an email-sending account in production to send the invitation.",
       T + "test_acceptance_accountant.py::test_accepting_an_invitation_grants_a_company_limited_accountant_membership",
       T + "test_acceptance_accountant.py::test_an_invitation_works_once",
       T + "test_acceptance_accountant.py::test_the_token_is_hashed_at_rest_and_never_recorded"),
    _c("X37", "Several managers per business.", "partial", SERVER,
       "Owner, accountant, employee and admin roles; an accountant can be limited to some companies. No per-outlet manager access.",
       T + "test_server_auth.py::test_accountant_reads_and_teaches_rules_only"),
    _c("X38", "Refunds linked to the original sale or placement.", "pass", DEMO,
       "Money back to a customer expects the business's own credit note, linked to its sales invoice.",
       T + "test_acceptance_live_obligations.py::test_money_back_to_a_customer_expects_your_own_credit_note",
       T + "test_acceptance_settlements.py::test_stripe_payout_with_fees_a_refund_and_a_dispute"),
)

CHECKS: dict[str, Check] = {c.id: c for _, _, checks in SECTIONS for c in checks} | {c.id: c for c in EXTRA}


# --------------------------------------------------------------------------- the 50 cases

def _k(number: int, title: str, quote: str, handles: list[tuple[str, str]], pass_test: str,
       decisive: list[str]) -> Case:
    return Case(number, title, quote, tuple(handles), pass_test, tuple(decisive))


CASES: tuple[Case, ...] = (
    _k(1, "Café owner",
       "I run a café. I buy food from multiple suppliers, pay utilities, receive card settlements, occasionally buy "
       "something personally for the café, and receive half my receipts on paper. I don't want to spend Sunday "
       "evening sorting receipts.",
       [("Supplier invoices by email", "X1"), ("Photographed receipts", "X2"), ("Card-terminal settlements", "I9"),
        ("Cash purchases", "X3"), ("Utility invoices behind web links", "C1"), ("Recurring rent", "X6"),
        ("Employee expenses", "X17"), ("VAT documents", "F3"), ("Missing supplier invoices", "K7")],
       "At month-end the owner photographs occasional cash receipts only. Everything else is collected, matched, "
       "checked and delivered to the accountant automatically.",
       ["X1", "C1", "I9", "K7", "N9"]),
    _k(2, "Restaurant",
       "We have dozens of suppliers, daily card settlement batches, food-delivery platforms and frequent credit notes. "
       "One supplier may invoice us ten times per month.",
       [("High document volume", "X33"), ("Glovo / Uber Eats / Bolt settlements", "X13"),
        ("Supplier statements", "X19"), ("Invoice versus credit-note relationships", "I8"),
        ("One settlement covering many orders", "X13"), ("Card and cash revenue evidence", "X5"),
        ("Recurring food suppliers", "L1"), ("Missing invoices", "K1")],
       "The system correctly distinguishes revenue settlements from expenses and closes supplier accounts without "
       "duplicating invoices.",
       ["X11", "X19", "G4"]),
    _k(3, "Bakery",
       "Raw-material prices change constantly. Suppliers issue invoices, delivery notes and occasional corrections. "
       "I don't know which document my accountant actually needs.",
       [("Invoice versus delivery note", "X18"), ("Invoice versus proforma", "X18"), ("Supplier statement", "X19"),
        ("Credit/debit notes", "I8"), ("Recurring ingredient purchases", "L1"), ("Price anomaly detection", "X20")],
       "Only valid accounting evidence is submitted. Supporting commercial documents remain attached but are not "
       "incorrectly booked as expenses.",
       ["X18"]),
    _k(4, "Small retail shop",
       "I buy inventory, pay rent, utilities and card fees. Some supplier invoices come in boxes with deliveries, "
       "others arrive by email.",
       [("Scanned paper invoices", "X2"), ("Card settlements", "I9"), ("Inventory supplier invoices", "X1"),
        ("Recurring landlord payments", "X6"), ("Utilities", "X6"), ("Supplier credit notes", "I8"),
        ("Duplicate paper/email invoice", "G3")],
       "The same invoice received physically and electronically is recognized as one expense.",
       ["G3", "X2"]),
    _k(5, "E-commerce store",
       "I sell through Shopify, Amazon and marketplaces. Payments arrive net of fees and refunds, while advertising is "
       "charged separately.",
       [("Shopify", "I10"), ("Stripe", "I10"), ("PayPal", "I10"), ("Amazon marketplace", "I10"), ("Refunds", "I10"),
        ("Payment processing fees", "I10"), ("Meta/Google ads", "P7"), ("Multicurrency", "I11"),
        ("Settlement aggregation", "I10")],
       "Gross sales, fees, refunds and net cash receipts reconcile correctly rather than treating the bank deposit as "
       "revenue by itself.",
       ["I10", "X11"]),
    _k(6, "Hair salon",
       "I have many small purchases, appointments, staff commissions and beauty suppliers. I mainly want something easy.",
       [("Small receipts", "X2"), ("Card expenses", "I1"), ("Recurring suppliers", "L1"), ("Rent", "X6"),
        ("Subscriptions", "X7"), ("Staff-related expenses", "X17"), ("Mobile receipt capture", "D15")],
       "Owner can scan a receipt in seconds without typing supplier, category, amount or VAT.",
       ["D1", "D15", "X2"]),
    _k(7, "Dental clinic",
       "We purchase medical equipment and consumables, use several service providers, and some invoices are large.",
       [("High-value equipment", "X21"), ("Recurring consumables", "L1"), ("Maintenance contracts", "M3"),
        ("Leasing", "X24"), ("Insurance", "M2"), ("Supplier IBAN changes", "Q1"),
        ("Expense versus capital-asset candidate flag", "X22")],
       "Large or unusual purchases receive stronger verification without creating unnecessary owner work for routine "
       "consumables.",
       ["X21", "X22"]),
    _k(8, "Physiotherapy clinic",
       "The business is simple but fragmented. Rent, software, contractors, equipment and professional insurance all "
       "arrive differently.",
       [("Recurring rent", "X6"), ("Contractor invoices", "X1"), ("Software subscriptions", "X7"),
        ("Insurance renewals", "M2"), ("Equipment receipts", "X2"), ("Tax obligations", "M1")],
       "Routine administration happens automatically and renewal deadlines are never missed.",
       ["M2", "M3"]),
    _k(9, "Gym",
       "We collect hundreds of recurring memberships while paying rent, utilities, instructors, equipment leasing and "
       "software.",
       [("Recurring revenue provider settlements", "I10"), ("Failed/refunded payments", "I6"),
        ("Equipment leasing", "X24"), ("Instructor invoices", "X1"), ("Utilities", "X6"),
        ("Subscription software", "X7"), ("Maintenance contracts", "M3")],
       "Revenue settlement totals reconcile to payment platforms and routine expenses require almost no owner "
       "involvement.",
       ["I10"]),
    _k(10, "Childcare business",
       "Parents pay monthly fees. We have staff, rent, food, insurance and licensing obligations. Missing a regulatory "
       "deadline is much worse than losing a receipt.",
       [("Recurring customer payments", "X12"), ("Licensing deadlines", "M4"), ("Insurance", "M2"),
        ("Payroll evidence", "J3"), ("Rent", "X6"), ("Supplier expenses", "X1"), ("Government correspondence", "M5")],
       "Financial and administrative obligations are both tracked, not merely invoices.",
       ["M4", "M5"]),
    _k(11, "Construction contractor",
       "Invoices are tied to projects. Suppliers send material invoices, subcontractors invoice us, clients pay in "
       "stages and retention may apply.",
       [("Project assignment", "X14"), ("Subcontractor invoices", "X1"), ("Material suppliers", "X1"),
        ("Staged client payments", "X8"), ("Deposits", "X8"), ("Partial payments", "I5"), ("Retention", "X8"),
        ("Credit notes", "I8")],
       "The system correctly associates expenses and payments with jobs without forcing the owner to classify every "
       "document manually.",
       ["X14"]),
    _k(12, "Electrician",
       "I am on sites all day. I buy materials in shops, receive some invoices by WhatsApp and send photos of receipts.",
       [("Mobile-first capture", "D1"), ("WhatsApp/share workflow", "D12"), ("Supplier receipts", "X2"),
        ("Van/fuel expenses", "X14"), ("Tool purchases", "X2"), ("Recurring wholesalers", "L1")],
       "The electrician can administer the business almost entirely from the phone.",
       ["D1", "D12", "X2"]),
    _k(13, "Plumber / HVAC company",
       "Technicians buy parts using company cards. I need to know which purchase relates to which job.",
       [("Several employee cards", "X16"), ("Mobile receipt uploads", "D7"), ("Project/customer matching", "X14"),
        ("Missing receipts", "K1"), ("Employee follow-up", "X16"), ("Vehicle costs", "X14")],
       "The system automatically asks the correct employee for missing evidence rather than asking the company owner.",
       ["X16"]),
    _k(14, "Architecture studio",
       "We have projects running for years. Consultants invoice us, clients pay milestones and many costs must be "
       "attributed to projects.",
       [("Long-running projects", "X14"), ("Consultant invoices", "X1"), ("Milestone billing", "X8"),
        ("Deposits", "X8"), ("Software subscriptions", "X7"), ("Project attribution", "X14")],
       "The system learns project-specific suppliers and substantially reduces manual project coding.",
       ["X14"]),
    _k(15, "Interior designer",
       "I purchase items on behalf of clients. Some purchases are reimbursable and some belong to my company.",
       [("Client-reimbursable expenses", "X10"), ("Company expenses", "X1"), ("Personal purchase mistakes", "X23"),
        ("Deposits", "X8"), ("Refunds", "I6"), ("Supplier orders", "X18")],
       "The system asks only when ownership/reimbursement genuinely cannot be inferred.",
       ["X10", "X23"]),
    _k(16, "Real-estate agency",
       "We have marketing, portals, photographers, commissions, rent and many individual agents.",
       [("Property portals", "X7"), ("Advertising", "P7"), ("Commissions", "X1"), ("Contractor invoices", "X1"),
        ("Subscriptions", "X7"), ("Multiple cards", "X14")],
       "Recurring subscriptions and agent-related costs are learned automatically.",
       ["X7", "X14"]),
    _k(17, "Property management company",
       "I manage many properties. Each building has different suppliers and owners.",
       [("Many cost centers", "X14"), ("Property-specific invoices", "X14"), ("Utilities", "X6"),
        ("Repairs", "X1"), ("Contractors", "X1"), ("Owner statements", "X25"),
        ("Reserve/maintenance expenses", "X14")],
       "An invoice can be reliably associated with the correct property without maintaining separate manual folders.",
       ["X14"]),
    _k(18, "Small hotel",
       "Booking sites pay us net of commissions. We also buy food, laundry, utilities and maintenance services.",
       [("Booking.com-style settlements", "X13"), ("OTA commission invoices", "X13"), ("Refunds", "I10"),
        ("Tourism-related fees", "X26"), ("Laundry", "X1"), ("Utilities", "X6"), ("Recurring suppliers", "L1")],
       "OTA settlement and commission logic reconciles correctly to bank receipts.",
       ["X13", "P7"]),
    _k(19, "Hostel",
       "Margins are tight. I need something cheap and automatic, not enterprise hospitality software.",
       [("Many low-value transactions", "X33"), ("Booking-platform settlements", "X13"), ("Utilities", "X6"),
        ("Card fees", "I9"), ("Employee expenses", "X17"), ("Petty cash", "X4")],
       "Processing cost is economically viable and the owner does not have to supervise the automation.",
       ["X34"]),
    _k(20, "Short-term rental operator",
       "I operate apartments. Cleaning, repairs, utilities, platform commissions and owner payments all need to be "
       "separated by property.",
       [("Airbnb/platform statements", "X13"), ("Property allocation", "X14"), ("Cleaning invoices", "X1"),
        ("Utilities", "X15"), ("Maintenance", "X1"), ("Landlord/owner payments", "X25")],
       "Each unit receives a complete evidence trail automatically.",
       ["X14", "X15"]),
    _k(21, "Law firm",
       "We receive professional-service invoices, court fees, client expenses, subscriptions and retainers.",
       [("Client-disbursement identification", "X10"), ("Professional subscriptions", "X7"),
        ("Retainers", "X8"), ("Court/government fees", "J2"), ("Confidential documents", "X32"),
        ("Several matters", "X14")],
       "Sensitive legal information is protected and client expenses are not incorrectly treated as firm expenses.",
       ["X32", "X10"]),
    _k(22, "Accounting firm",
       "My biggest waste is chasing 100 clients for missing documents.",
       [("Accountant multi-client dashboard", "N1"), ("Document completeness", "N2"), ("Client invitations", "X36"),
        ("Missing-document automation", "K7"), ("Client-specific rules", "N6"), ("Bulk status view", "N1")],
       "The accountant can immediately see which clients are complete and which specific items remain unresolved.",
       ["N1", "N3"]),
    _k(23, "Marketing agency",
       "We buy advertising on behalf of clients and have dozens of software subscriptions.",
       [("Reimbursable advertising", "X10"), ("Meta/Google invoices", "P7"), ("SaaS subscriptions", "X7"),
        ("Client allocation", "X14"), ("Contractor invoices", "X1"), ("Multicurrency", "I11")],
       "Client media spend is separated correctly from agency overhead.",
       ["X14", "X10"]),
    _k(24, "Software development agency",
       "Developers use many cloud services. Some charges are project-specific; others are shared overhead.",
       [("AWS/Azure/GCP", "X27"), ("GitHub", "X27"), ("AI APIs", "X27"), ("SaaS tools", "X7"),
        ("Contractors", "X1"), ("FX charges", "I11"), ("Project attribution", "X14")],
       "Cloud invoices and card transactions reconcile even when vendor descriptors differ.",
       ["X27", "I11"]),
    _k(25, "SaaS startup",
       "We collect subscription revenue globally and pay dozens of cloud/software vendors.",
       [("Stripe", "I10"), ("Recurring revenue", "X12"), ("Refunds", "I10"), ("Chargebacks", "I7"),
        ("Multicurrency", "I11"), ("SaaS expenses", "X7"), ("Cloud infrastructure", "X27"),
        ("Investor/legal expenses", "X1")],
       "Settlement reconciliation works without manually reconstructing Stripe transactions.",
       ["I10"]),
    _k(26, "IT managed-service provider",
       "We buy licenses for customers and resell them. One vendor invoice may cover dozens of customers.",
       [("Reseller invoices", "X15"), ("Customer allocation", "X14"), ("Recurring licenses", "L1"),
        ("Pass-through costs", "X10"), ("Vendor credits", "I8")],
       "The system can split one supplier document across multiple customers/cost centers.",
       ["X15"]),
    _k(27, "Recruitment agency",
       "Revenue depends on placement milestones. Contractors, job platforms and software generate recurring costs.",
       [("Milestone revenue", "X8"), ("Refunds/replacement guarantees", "X38"), ("Subscriptions", "X7"),
        ("Recruiter expenses", "X17"), ("Contractor invoices", "X1")],
       "Revenue and refunds remain linked to the correct placement/customer.",
       ["X8", "X38"]),
    _k(28, "Solo consultant",
       "I have very few transactions. I refuse to pay €50/month or spend time configuring software.",
       [("Minimal onboarding", "A1"), ("Low-volume pricing", "X35"), ("Email invoices", "X1"),
        ("Travel expenses", "X2"), ("Subscriptions", "X7"), ("Accountant handoff", "N9")],
       "The product provides visible value within five minutes and remains cheaper than the owner's lost "
       "administrative time.",
       ["U2", "X35"]),
    _k(29, "Photographer",
       "I travel, buy equipment, hire assistants and receive deposits before shoots.",
       [("Deposits", "X8"), ("Final client payments", "X11"), ("Equipment", "X22"), ("Travel", "X2"),
        ("Assistants", "X1"), ("Reimbursable costs", "X10")],
       "Deposits and final revenue are not double-counted.",
       ["X8"]),
    _k(30, "Event planner",
       "Every event is effectively a mini-project with dozens of suppliers.",
       [("Event cost centers", "X14"), ("Client deposits", "X8"), ("Supplier deposits", "I4"),
        ("Final balances", "X8"), ("Cancellations", "I6"), ("Refunds", "I6")],
       "The complete financial evidence for one event can be viewed independently.",
       ["X14"]),
    _k(31, "Wedding venue",
       "Couples pay deposits and balances. Catering, staff, decorators and suppliers vary by event.",
       [("Event-specific revenue", "X14"), ("Deposits", "X8"), ("Final settlement", "X8"),
        ("Outsourced suppliers", "X1"), ("Refunds", "I6"), ("Seasonal patterns", "X29")],
       "Each wedding/event can be financially reconstructed without manual folder creation.",
       ["X14"]),
    _k(32, "Travel agency",
       "Client money often passes through us before being paid to airlines, hotels or tour providers.",
       [("Pass-through money", "X10"), ("Commissions", "X13"), ("Supplier settlements", "X10"), ("Refunds", "I6"),
        ("FX", "I11"), ("Cancellations", "I6")],
       "Client funds are not incorrectly treated as agency revenue where accounting policy says otherwise.",
       ["X10"]),
    _k(33, "Car rental business",
       "We have fleet leasing, repairs, insurance, tolls, fines, fuel and customer deposits.",
       [("Vehicle-level cost centers", "X14"), ("Insurance renewals", "M2"), ("Deposits", "X9"), ("Refunds", "I6"),
        ("Tolls", "X14"), ("Repair bills", "X1"), ("Fines", "X14"), ("Leasing", "X24")],
       "Costs can be tied to individual vehicles and security deposits are distinguished from revenue.",
       ["X14", "X9"]),
    _k(34, "Auto repair shop",
       "I buy parts constantly. Suppliers send delivery notes, invoices and monthly statements.",
       [("Parts suppliers", "X1"), ("Delivery notes", "X18"), ("Invoices", "X1"), ("Statement reconciliation", "X19"),
        ("Customer/job assignment", "X14"), ("Returns/credits", "I8")],
       "Supplier statements reconcile to underlying invoices without duplicate booking.",
       ["X19"]),
    _k(35, "Courier / logistics company",
       "Fuel, tolls, repairs, drivers and vehicle costs dominate the business.",
       [("Many vehicles", "X14"), ("Fuel cards", "X14"), ("Toll accounts", "X14"), ("Repair invoices", "X1"),
        ("Driver expenses", "X17"), ("Insurance", "M2"), ("Leasing", "X24")],
       "Recurring vehicle expenses are mapped automatically by vehicle/card.",
       ["X14"]),
    _k(36, "Import / export wholesaler",
       "We buy abroad, pay freight, customs, duties and sometimes deposits months before the goods arrive.",
       [("Foreign-currency invoices", "I11"), ("Import duty", "X28"), ("Customs documents", "X28"),
        ("Freight", "X28"), ("Deposits", "I4"), ("Later final invoices", "X28"), ("FX differences", "I11")],
       "The complete purchase chain remains linked rather than appearing as unrelated transactions.",
       ["X28"]),
    _k(37, "Small manufacturer",
       "We buy raw materials, machinery, spare parts and services. Some purchases are normal costs; others are capital "
       "equipment.",
       [("Material suppliers", "X1"), ("Equipment", "X22"), ("Maintenance", "M3"), ("Recurring utilities", "X6"),
        ("Freight", "X1"), ("Capital-asset candidates", "X22")],
       "High-value equipment is flagged for accountant review rather than silently classified as ordinary expense.",
       ["X22"]),
    _k(38, "Food producer",
       "We purchase ingredients, packaging and logistics services and receive frequent supplier credits.",
       [("Raw materials", "X1"), ("Packaging", "X1"), ("Freight", "X1"), ("Recurring vendors", "L1"),
        ("Credit notes", "I8"), ("Quality-related refunds", "I6")],
       "Credit notes automatically reconcile to the correct original invoice where possible.",
       ["I8"]),
    _k(39, "Winery",
       "The business is seasonal. We have agriculture, production, packaging, tourism and export costs.",
       [("Seasonal spending", "X29"), ("Multiple business activities", "X14"), ("Equipment", "X22"),
        ("Agricultural suppliers", "X1"), ("Export documents", "X28"), ("Tourism revenue", "X11")],
       "Cost-center inference works without creating separate businesses/accounts for every activity.",
       ["X14"]),
    _k(40, "Farm",
       "Many purchases happen locally. Some receipts are dirty photographs. Government and subsidy communications "
       "matter too.",
       [("Poor receipt images", "E10"), ("Agricultural suppliers", "X1"), ("Fuel", "X14"), ("Equipment", "X22"),
        ("Subsidy/grant communications", "X30"), ("Government deadlines", "M5")],
       "Image quality recovery and obligation detection work even when documents are imperfect.",
       ["E10", "X30"]),
    _k(41, "Cleaning company",
       "Employees work across many client locations and buy cleaning materials using several cards.",
       [("Employee cards", "X16"), ("Location/client allocation", "X14"), ("Mileage/fuel", "X14"),
        ("Supplies", "X1"), ("Payroll-related evidence", "J3"), ("Mobile submissions", "D7")],
       "Missing receipts are chased from the employee responsible, not the owner.",
       ["X16"]),
    _k(42, "Security services company",
       "We have payroll-heavy operations, uniforms, vehicles, subcontractors and regulatory obligations.",
       [("Regulatory deadlines", "M4"), ("Uniforms/equipment", "X1"), ("Vehicle costs", "X14"),
        ("Subcontractors", "X1"), ("Payroll evidence", "J3"), ("Insurance", "M2")],
       "Compliance reminders are treated as seriously as financial evidence.",
       ["M4", "M5"]),
    _k(43, "Building maintenance company",
       "We maintain many properties. Technicians buy parts and subcontract specialist work.",
       [("Property/job allocation", "X14"), ("Technicians", "X16"), ("Cards", "X14"), ("Subcontractors", "X1"),
        ("Parts receipts", "X2"), ("Recurring service contracts", "M3")],
       "The system can infer job/property allocation from context and history.",
       ["X14"]),
    _k(44, "Training business",
       "We run courses, hire trainers, rent spaces and sell both to individuals and companies.",
       [("Course-level cost centers", "X14"), ("Trainer invoices", "X1"), ("Venue rental", "X1"),
        ("Refunds", "I6"), ("Customer payments", "X11"), ("Software tools", "X7")],
       "Each course can be evaluated financially without manual reconciliation.",
       ["X14"]),
    _k(45, "Language school",
       "Students pay monthly or per term. Teachers may be employees or contractors.",
       [("Recurring student payments", "X12"), ("Refunds", "I6"), ("Teacher invoices", "X1"), ("Rent", "X6"),
        ("Education software", "X7"), ("Multi-period revenue evidence", "X12")],
       "Recurring receipts and contractor documents are correctly distinguished.",
       ["X11", "X12"]),
    _k(46, "Small pharmacy / health retailer",
       "We purchase from many wholesalers and deal with frequent credit notes and supplier statements.",
       [("High invoice volume", "X33"), ("Supplier statements", "X19"), ("Credits", "I8"),
        ("Inventory vendors", "X1"), ("Strict access controls", "X32"), ("Banking reconciliation", "I1")],
       "High-volume supplier reconciliation is reliable without exposing sensitive data unnecessarily.",
       ["X33", "X32"]),
    _k(47, "Veterinary clinic",
       "We buy medicines, supplies, equipment and laboratory services while collecting hundreds of client payments.",
       [("Many suppliers", "X1"), ("Equipment", "X22"), ("Lab invoices", "X1"), ("Recurring subscriptions", "X7"),
        ("Card settlements", "I9"), ("Insurance/licensing", "M4")],
       "Routine expenses disappear into automation while unusual/high-value costs surface appropriately.",
       ["X21", "X22"]),
    _k(48, "Franchise operator",
       "I have several outlets under one company and pay royalties, marketing fees and common suppliers.",
       [("Location cost centers", "X14"), ("Royalties", "X1"), ("Central supplier invoices", "X15"),
        ("Outlet-level bank/card activity", "X14"), ("Shared costs", "X15"), ("Multiple managers", "X37")],
       "Owner can view each outlet separately while maintaining one legal entity.",
       ["X14"]),
    _k(49, "Cross-border SME",
       "My company is Portuguese but we buy services from the US, UK and EU and invoice foreign customers.",
       [("Multiple currencies", "I11"), ("Reverse-charge candidates", "X31"), ("Foreign VAT", "X31"),
        ("FX", "I11"), ("International vendors", "P7"), ("Non-Portuguese document formats", "P7"),
        ("Country-specific rules", "O6")],
       "The system does not assume every document follows Portuguese formatting merely because the company is "
       "Portuguese.",
       ["P7"]),
    _k(50, "Multi-company owner",
       "I own several companies. I often receive documents in one inbox and pay expenses from different accounts. My "
       "biggest problem is deciding which entity everything belongs to.",
       [("Multiple legal entities", "O1"), ("Shared email account", "O2"), ("Several banks/cards", "O4"),
        ("Intercompany transactions", "H8"), ("Wrong-entity payments", "H9"), ("Shared suppliers", "O3"),
        ("Different accountants", "O5"), ("Different jurisdictions", "O6")],
       "Owner sees one global control center while every underlying document, transaction and obligation remains "
       "legally separated and auditable.",
       ["O8", "O7", "H9"]),
)

FINAL_TEST = {
    "question": "What administrative work did you personally do this month that you believe the system should "
                "have done for you?",
    "categories": ["Product defect", "Missing integration", "Missing automation", "Intentional approval boundary"],
    "rule": "There should be no fifth category called “That is just something users have to do.”",
    "status": "missing",
    "note": "Nothing asks this question after 30 days or sorts the answers yet. This QA page is the manual version: "
            "every gap found becomes one of the four categories.",
}

PURPOSE = ("These are not marketing personas. They are production acceptance scenarios. The product should "
           "ultimately be able to satisfy all 50 without changing its fundamental architecture. If the system "
           "repeatedly forces the owner to perform administrative work described below, the relevant case has "
           "failed.")


# --------------------------------------------------------------------------- verdicts

def _combine(statuses: list[Status]) -> Status:
    if statuses and all(s == "pass" for s in statuses):
        return "pass"
    if statuses and all(s == "missing" for s in statuses):
        return "missing"
    return "partial"


def _check_row(c: Check) -> dict[str, Any]:
    return {"id": c.id, "text": c.text, "status": c.status, "where": c.where, "note": c.note,
            "evidence": list(c.evidence)}


def _counts(statuses: list[Status]) -> dict[str, int]:
    return {"pass": statuses.count("pass"), "partial": statuses.count("partial"),
            "missing": statuses.count("missing"), "total": len(statuses)}


def _case_row(k: Case) -> dict[str, Any]:
    decisive = [CHECKS[i].status for i in k.decisive]
    pass_test = _combine(decisive)
    handled = [CHECKS[ref].status for _, ref in k.handles]
    covered = handled.count("pass")
    if pass_test == "pass" and covered == len(handled):
        verdict: Status = "pass"
    elif pass_test == "missing":
        verdict = "missing"
    else:
        verdict = "partial"
    gaps = []
    seen: set[str] = set()
    for text, ref in k.handles:
        c = CHECKS[ref]
        if c.status != "pass" and ref not in seen:
            seen.add(ref)
            gaps.append({"id": ref, "text": c.text, "status": c.status, "note": c.note})
    for ref in k.decisive:
        c = CHECKS[ref]
        if c.status != "pass" and ref not in seen:
            seen.add(ref)
            gaps.append({"id": ref, "text": c.text, "status": c.status, "note": c.note})
    return {
        "number": k.number, "title": k.title, "quote": k.quote, "verdict": verdict,
        "passTest": {"text": k.pass_test, "status": pass_test,
                     "checks": [{"id": i, "text": CHECKS[i].text, "status": CHECKS[i].status} for i in k.decisive]},
        "handles": [{"text": text, "check": ref, "status": CHECKS[ref].status, "where": CHECKS[ref].where,
                     "note": CHECKS[ref].note} for text, ref in k.handles],
        "covered": covered, "handled": len(handled),
        "gaps": gaps,
    }


def acceptance() -> dict[str, Any]:
    """The QA page: every case and check with its verdict and the totals (JSON-able)."""
    sections = []
    all_checks: list[Status] = []
    for letter, title, checks in SECTIONS:
        statuses = [c.status for c in checks]
        all_checks += statuses
        sections.append({"id": letter, "title": title, "counts": _counts(statuses),
                         "checks": [_check_row(c) for c in checks]})
    cases = [_case_row(k) for k in CASES]
    verdicts = [c["verdict"] for c in cases]
    pass_tests = [c["passTest"]["status"] for c in cases]
    checklist = _counts(all_checks)
    return {
        "purpose": PURPOSE,
        "legend": {
            "pass": "Works in the engine and is proven by a named automated test.",
            "partial": "Some of it works, or it is built but not connected, or it needs accounts or keys.",
            "missing": "Not built.",
        },
        "summary": {
            "cases": _counts(verdicts),
            "passTests": _counts(pass_tests),
            "checklist": checklist,
            "percent": checklist["pass"] * 100 // checklist["total"] if checklist["total"] else 0,
            "sector": _counts([c.status for c in EXTRA]),
        },
        "sections": sections,
        "sector": [_check_row(c) for c in EXTRA],
        "cases": cases,
        "finalTest": FINAL_TEST,
    }
