"""Supplier portal adapters (§10). Deterministic first; AI browser only as fallback."""

from .base import (
    AuthResult,
    AuthStatus,
    MfaChallenge,
    PortalChanged,
    PortalCredentials,
    PortalDocument,
    PortalError,
    PortalInvoiceRef,
    PortalRegistry,
    PortalSession,
    PortalSync,
    PortalSyncOutcome,
    RetrievalPlan,
    RetrievalStrategy,
    SupplierPortalConnector,
    authentication_prompt,
    code_prompt,
    default_registry,
    plan_retrieval,
    register_portal,
)

__all__ = [
    "AuthResult",
    "AuthStatus",
    "MfaChallenge",
    "PortalChanged",
    "PortalCredentials",
    "PortalDocument",
    "PortalError",
    "PortalInvoiceRef",
    "PortalRegistry",
    "PortalSession",
    "PortalSync",
    "PortalSyncOutcome",
    "RetrievalPlan",
    "RetrievalStrategy",
    "SupplierPortalConnector",
    "authentication_prompt",
    "code_prompt",
    "default_registry",
    "plan_retrieval",
    "register_portal",
]
